---
title: "sim EBCI Cell"
format: html
editor: source
theme: sandstone
toc: true
toc-depth: 2
execute: 
  echo: true
  warning: false
---



v2: put functions into a utils file

# Setup/Load

```{r}
# libraries
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
ggplot2::theme_set(theme_bw() + theme(plot.title = element_text(hjust = .5), panel.grid.minor = element_blank()))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ebci)) # robust emp shrinkage
suppressPackageStartupMessages(library(lpSolve))
suppressPackageStartupMessages(library(assertthat)) 
suppressPackageStartupMessages(library(softImpute))
suppressPackageStartupMessages(library(latex2exp))
suppressPackageStartupMessages(library(future.apply))
plan(multisession, workers = 4)  # or some other plan

# our code
source('../../utils/matrix_shrinkage.r')
source('../matrixPrior/matrixPrior_utils.R') # may have a different 'create blocky matrix' version


source('../../utils/simEBCICell_utils.R') 


```




# Script


```{r output=FALSE, eval=FALSE}
#| eval: FALSE
#| output: FALSE





# libraries
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
ggplot2::theme_set(theme_bw())
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(ebci)) # robust emp shrinkage
suppressPackageStartupMessages(library(assertthat)) 
suppressPackageStartupMessages(library(softImpute))
suppressPackageStartupMessages(library(latex2exp))
suppressPackageStartupMessages(library(future.apply))
plan(multisession, workers = 4)  # or some other plan
# our code
source('../../utils/matrix_shrinkage.r')
source('../matrixPrior/matrixPrior_utils.R') # may have a different 'create blocky matrix' version

source('../../utils/simEBCICell_utils.R') 



# simulations


ALPHA = .1 # PARAMETER
overall_save_folder = '../../plots/simEBCICell/' # dir.create(shrinkage_plots_folder)


# === SETTING A === (small, easy, fast setting)
set.seed(12345)
setting_name = 'A'
P=5
G=10
rank=2
ThetaA = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=ThetaA,            # true effects ( input NULL if want to simulate)
  N=500,                 # number of treated cells
  N_control=500,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 2, 3),       # ranks for matrix approximations
  save_folder=save_folder,# folder to save results and plots
  make_plots = FALSE
)

# N=500; N_control=500; nb_size=3; ranks=c(1,2,3)
t1 = Sys.time(); print(t1 - t0) # 8  24 sec w/o plots, 1.7 mins with plots??




# === SETTING B === (slightly larger, ) 
set.seed(12345)
setting_name = 'B'
P=10
G=20
rank=3
Theta = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=Theta,            # true effects ( input NULL if want to simulate)
  N=1000,                 # number of treated cells
  N_control=500,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 2, 3),       # ranks for matrix approximations
  save_folder=save_folder,# folder to save results and plots
  make_plots = FALSE
)
t1 = Sys.time(); print(t1 - t0) # 1.4  mins without plots, 3.x with plots


# === SETTING C === (even larger, )
set.seed(12345)
setting_name = 'C'
P=25
G=200
rank=3
Theta = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=Theta,            # true effects ( input NULL if want to simulate)
  N=2500,                 # number of treated cells
  N_control=500,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 2, 3),       # ranks for matrix approximations
  save_folder=save_folder,# folder to save results and plots
  make_plots = FALSE
)
t1 = Sys.time(); print(t1 - t0) # 




# === SETTING D === (even larger? )
set.seed(12345)
setting_name = 'D'
P=50
G=500
rank=3
Theta = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=Theta,            # true effects ( input NULL if want to simulate)
  N=5000,                 # number of treated cells
  N_control=500,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 2, 3),       # ranks for matrix approximations
  save_folder=save_folder,# folder to save results and plots
  make_plots = FALSE
)
t1 = Sys.time(); print(t1 - t0) # 



# === SETTING E === (smaller sample size (larger noise))
set.seed(12345)
setting_name = 'E'
P=50
G=500
rank=3
Theta = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=Theta,            # true effects ( input NULL if want to simulate)
  N=2000,                 # number of treated cells
  N_control=200,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 2, 3),       # ranks for matrix approximations
  save_folder=save_folder,# folder to save results and plots
  make_plots = FALSE
)
t1 = Sys.time(); print(t1 - t0) #




# === SETTING F === (rank increase)
set.seed(12345)
setting_name = 'F'
P=50
G=500
rank=5
Theta = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=Theta,            # true effects ( input NULL if want to simulate)
  N=5000,                 # number of treated cells
  N_control=500,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 3, 5),       # ranks for matrix approximations
  save_folder=save_folder,# folder to save results and plots
  make_plots = FALSE
)
t1 = Sys.time(); print(t1 - t0) # 




```

# create plots from save



```{r}
#| eval: true
#| output: false
#| warning: false
#| include: false

# make the matrix and mse plots for all the settings
for(setting_name in c('A', 'B', 'C', 'D', 'E', 'F', 'G')) {
  # load in save and create sim specific plots
  save_folder = sprintf('../../plots/simEBCICell/%s', setting_name)
  # sim_results = readRDS(sprintf('%s/sim_results.rds', save_folder))
  
  
  make_plots_from_save(sim_results_filenames=sprintf('%s/sim_results.rds', save_folder),
                       save_folder=save_folder,
                       which_plots = list(matrix=TRUE, mse=TRUE, miscoverage=TRUE),
                       write_plot_df = FALSE)
}


```

# Create Plots (working)

```{r}


# load in save and create sim specific plots
save_folder = '../../plots/simEBCICell/A'
# save_folder = '../../plots/simEBCICell/D'
sim_results = readRDS(sprintf('%s/sim_results.rds', save_folder))
# sim_results$ALPHA = .1
ranks = sim_results$ranks
names(sim_results)
names(sim_results$shrinkage_results$pois$samplesplit$zeros)
Matrix::rankMatrix(sim_results$Theta) |> as.numeric() # find the rank of Theta (package Matrix, fn rankMatrix)
plot_df = h5_0_create_plot_df(shrinkage_results = sim_results$shrinkage_results, 
                              allcells_results  = sim_results$allcells_results, 
                              ranks             = sim_results$ranks, 
                              ALPHA             = sim_results$ALPHA)


head(plot_df); dim(plot_df)
# h5_3_plots_mse(plot_df=plot_df, ranks=sim_results$ranks, save_folder=save_folder) 
unique(plot_df$method)




which_plots = list(matrices  = TRUE,
                   mse       = TRUE,
                   CIlengths = TRUE,
                   rejrate   = TRUE)



clean_methodrank_names <- function(x) {
  
  
  
}

method_nicenames = list(unshrunk='GLM (sample split)',
                        unshrunkallcells='GLM (all data)',
                        matcomp_linearreg='EBCI (lin reg)',
                        matcomp_softImpute='EBCI (softImpute)')


method_nicenames[['unshrunk']]

gsub(pattern = "NA", replacement = "", x = "unshrunkallcellsNA")

matrices

# display the matrices

make_matrix_ebci_plots(..)





# QQ-plots/rejection rates?

plot_df |> 
       filter(method != 'matcomp_linearreg') |>
       group_by(sim_distn, split_type, method, rank) |> 
       arrange(...)
       summarize(mse = mean((shrunk_value - true_theta)^2)) 

       
       
         ebci_obj = ebci::ebci(formula = sprintf('%s - shrinkage_point ~ 0', 'unshrunk_value'),
                        # formula = 'tstat - shrinkage_point ~ 0', # ebci_formula
                        # data    = ebci_data, # |> dplyr::mutate(my_weights = 1/n()), 
                        data = sim_results$shrinkage_results$nb$samplesplit$zeros,
                        # se = eval(parse(text = se_colname)), 
                        # weights =  eval(parse(text = sprintf('1/%s^2', se_colname))), 
                        # TODO: set weights, prob 1/n
                        se = se,
                        weights = weight,
                        # weights = 1/nrow(ebci_data),
                        alpha = sim_results$ALPHA)
         
        
         # maybe just write a custom function...
         # 
         my_mu2 = ebci_obj$mu2[['estimate']]
         my_kappa = ebci_obj$kappa[['estimate']]
         # search for alpha
         cur_alpha = .3
         ebci::cva(m2 = my_mu2, kappa = my_kappa, check=FALSE, alpha = cur_alpha)
         
         ebci_obj$df |> head()
         
         
         # the CI is formed by
         # \hat{\theta} +- cva_\alpha(m2i=sigma_i^2 / mu2, kappa) * w_eb * sigma_i
         # to find the pseudo p-value...
         # \hat{\theta} +- cva_\alpha(m2i, kappa) * w_eb * sigma_i
         # Find the smallest alpha level such that this CI does not cover 0
         # or
         # find the largest alpha such that this CI covers 0
         #
         # e.g. large
         al_ = seq(from = .01, to = .99, length.out = 20)
         plot(al_, sapply(X = al_, FUN = function(al) {ebci::cva(m2 = my_mu2, kappa = my_kappa, check=FALSE, alpha = al)$cv}))
         for(i in 1:10)  {ebci::cva(m2 = my_mu2, kappa = my_kappa, check=FALSE, alpha = cur_alpha)$cv |> print()}
         
         
         #' description: Create the pseudo p-value: Find the smallest alpha that does not cover 0 OR the largest alpha that still covers 0
         #'  The CI is shrunk estimate +- cva * w_eb * sigma
         #'  because of the way we call the function, we have our original estimate thetahat and shrinkagepoint
         #'  and we shrink (thetahat - shrinkagepoint) towards 0 always to then get thetaeb(this is because we have diff shrinkage points for all the points)
         #'  and then we add back the shrinkage point shrunkpoint = thetaeb + shrinkagepoint <-- this is the value to to input into this function, because the CI is centered around this point
         #' @param thetashrunk (numeric)
         #' @param sigma (numeric)
         #' @param web (numeric) shrinkage factor from ebci object result
         #' @param mu2 (numeric) estimated mu2 from ebci object result
         #' @param kappa (numeric) estimated kappa from ebci object result
         #' @param threshold (numeric) stop condition: perform until alpha's changes are < threshold
         #'                            this is the max mis calc error for the pseudo-pval (if MAX_ITER is not reached)
         #' @param maxiter (numeric) stop condition: maximum number of iterations to perform
         #' 
         #' @returns pseudopval (numeric) \in [0,1]
         #' 
         #' 
         get_ebci_average_pvals <- function(thetashrunk, sigma, web, mu2, kappa,
                                            threshold, maxiter) {
           # params for running 
           MAX_ITER_FOR_P = 20    # limit the number of iterations
           # distance_threshold  = .001 # distance between (my_theta / (my_web * my_sigma)) and cva_pseudop(m2, kappa)
           alpha_threshold = .0001 # perform until changes in alpha are small (ie this is the rounding of the p-value, there will be at most log2(1/alpha_threshold) iterations)
           # estimate from overall ebci fit
           my_mu2 = ebci_obj$mu2[['estimate']]
           my_kappa = ebci_obj$kappa[['estimate']]
           # params for each sample i 
           my_theta = .2 # shrunk estimate: should be ebci_obj$df$th_eb + shrinkage_point (e.g. not the 'raw' the_eb)
           my_sigma = 1 # initial estimate standard error
           my_web = .3   # shrinkage factor
           
           # helpful calcs to just perform once
           sigma2_mu2 = my_sigma^2 / my_mu2  # = m2 in cva function input
           theta_websigma = abs(my_theta) / (my_web * my_sigma) # |theta| / (w_eb * sigma)   normalized estimate, always > 0
           
           
           
           iter = 1
           cur_min = 0; cur_max = 1 # range to search for pseudo p-value
           cur_alpha = .5 # start in the middle
           track_alphas = c(cur_alpha)
           # distance = 10000
           alpha_change = 1
           # while(distance > distance_threshold & iter <= MAX_ITER_FOR_P) { # by theta_websigma - cur_cva_alpha
           while(alpha_change > alpha_threshold & iter <= MAX_ITER_FOR_P) { # by alpha/p-value change
             cur_cva_alpha = ebci::cva(m2 = sigma2_mu2, kappa = my_kappa, check=FALSE, alpha = cur_alpha)$cv
             print(sprintf("%d: %.8f [%.2f, %.2f]: %.2f vs %.2f", 
                            iter, cur_alpha, cur_min, cur_max, theta_websigma, cur_cva_alpha))
             
             # check if 0 is in CI with cur_alpha
             if(theta_websigma - cur_cva_alpha < 0) { # 0 \in CI: increase alpha to make CI smaller
               cur_min = cur_alpha  
               new_alpha = (cur_alpha + cur_max) / 2
             } else { # 0 \not\in CI: decrease alpha to make CI larger
               cur_max = cur_alpha
               new_alpha = (cur_alpha + cur_min) / 2
             }
             
             
             alpha_change = abs(new_alpha - cur_alpha)
             cur_alpha = new_alpha
             
             track_alphas = c(track_alphas, cur_alpha)
             
             # distance = theta_websigma - cur_cva_alpha
             iter = iter + 1
           }
           
           return(cur_alpha)
         }
         
         
         
         
         
         
  # t1 = Sys.time(); print(t1 - t0)
  
  ebci_res = ebci_data |> 
    # head(nrow(ebci_obj$df)) |>
    dplyr::mutate(shrunk_value = ebci_obj$df$th_eb + shrinkage_point,
                  lower_ci = shrunk_value - ebci_obj$df$len_eb,
                  upper_ci = shrunk_value + ebci_obj$df$len_eb)
  
  
  


  
  
  
# CI interval

# Error by shrinkage distance?

# Error by shrinkage

  
  
# CI Coverage of 0 (ie reject or accept)

ggplot(plot_df |>  mutate(test_type = sapply(true_theta, function(th) {if(th==0){'Null'} else {'Alt'}}))  |>
  group_by(sim_distn, split_type, method, rank, test_type) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), 
                   rejected = mean(is_sig),
                   .groups = 'drop') |> 
         arrange(sim_distn, method, rank, test_type) |> 
         mutate(methodrank = factor(paste0(method, rank), 
                                    levels = c("unshrunkallcellsNA",
                                               "unshrunkNA", 
                                               "matcomp_linearregNA", 
                                               paste0("matcomp_softImpute", ranks), 
                                               paste0("matdecomp_svd", ranks),
                                               paste0("matdecomp_sparsesvd", ranks)))),
  aes(x = methodrank, y = rejected)) +
  geom_hline(aes(yintercept = ALPHA), color = 'orange', alpha = .7) +
  geom_col() +
  facet_grid(cols = vars(test_type), rows = vars(sim_distn)) +
  # coord_cartesian(ylim= c(0, .009)) +
  labs(title = sprintf('Proportion of Tests Rejected   %s', substr(save_folder, nchar(save_folder) - 1, nchar(save_folder)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

ggsave(filename = sprintf('%s/shrinkage_rej.pdf', save_folder), width = 6, height = 6)
```




```{r}
# MSE
ggplot(plot_df |> 
       filter(method != 'matcomp_linearreg') |>
       group_by(sim_distn, split_type, method, rank) |> 
       summarize(mse = mean((shrunk_value - true_theta)^2)) |> 
       arrange(sim_distn, split_type, method, rank) |> 
       mutate(methodrank = factor(paste0(method, rank), 
                              levels = c("unshrunkallcellsNA",
                                         "unshrunkNA", 
                                         "matcomp_linearregNA", 
                                         paste0("matcomp_softImpute", ranks), 
                                         paste0("matdecomp_svd", ranks),
                                         paste0("matdecomp_sparsesvd", ranks), 
                                         "zerosNA", 
                                         "averageNA"))), 
     aes(x = methodrank, y = mse)) +
  geom_col(color = 'black', fill = 'gray') +
  facet_grid(rows = vars(sim_distn), cols = vars(split_type), scales = 'free_y') +
  labs(title = 'MSE', x = 'method + rank', y = 'mse') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

```


```{r}

# CI Coverage (should be 1-alpha proportion) # Mis-coverage rate to compare with mse (lower is better)

# coverage rate
# ggplot(plot_df |> 
#        filter(method != 'matcomp_linearreg') |>
#        mutate(isTrueThetaCovered = as.integer( lower_ci <= true_theta & true_theta <= upper_ci)) |>
#        group_by(sim_distn, split_type, method, rank) |> 
#        summarize(average_coverage = mean(isTrueThetaCovered), .groups = 'drop') |> 
#        arrange(sim_distn, split_type, method, rank) |> 
#        mutate(methodrank = factor(paste0(method, rank), 
#                               levels = c("unshrunkallcellsNA",
#                                          "unshrunkNA", 
#                                          "matcomp_linearregNA", 
#                                          paste0("matcomp_softImpute", ranks), 
#                                          paste0("matdecomp_svd", ranks),
#                                          paste0("matdecomp_sparsesvd", ranks), 
#                                          "zerosNA", 
#                                          "averageNA"))), 
#      aes(x = methodrank, y = average_coverage)) +
#   geom_col(color = 'black', fill = 'gray') +
#   geom_hline(aes(yintercept = 1 - sim_results$ALPHA), color = 'orange', alpha = .7) +
#   facet_grid(rows = vars(sim_distn), cols = vars(split_type), scales = 'free_y') +
#   labs(title = 'Average EBCI Coverage', x = 'method + rank', y = 'average coverage') +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), panel.grid.major.x = element_blank())

# miscoverage rate
ggplot(plot_df |> 
       filter(method != 'matcomp_linearreg') |>
       mutate(isTrueThetaCovered = as.integer( lower_ci <= true_theta & true_theta <= upper_ci)) |>
       group_by(sim_distn, split_type, method, rank) |> 
       summarize(miscoverage_rate = 1 - mean(isTrueThetaCovered), .groups = 'drop') |> 
       arrange(sim_distn, split_type, method, rank) |> 
       mutate(methodrank = factor(paste0(method, rank), 
                              levels = c("unshrunkallcellsNA",
                                         "unshrunkNA", 
                                         "matcomp_linearregNA", 
                                         paste0("matcomp_softImpute", ranks), 
                                         paste0("matdecomp_svd", ranks),
                                         paste0("matdecomp_sparsesvd", ranks), 
                                         "zerosNA", 
                                         "averageNA"))), 
     aes(x = methodrank, y = miscoverage_rate)) +
  geom_col(color = 'black', fill = 'gray') +
  geom_hline(aes(yintercept = sim_results$ALPHA), color = 'orange', alpha = .7) +
  facet_grid(rows = vars(sim_distn), cols = vars(split_type), scales = 'free_y') +
  labs(title = 'EBCI Miscoverage Rate', x = 'method + rank', y = 'miscoverage rate') +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), panel.grid.major.x = element_blank())

ggsave(filename = sprintf('%s/ebci_miscoveragerate.pdf', save_folder), width = 6, height = 6) 

```







# working out stuff

```{r}
# load in save and create sim specific plots
save_folder = '../../plots/simEBCICell/D'
sim_results = readRDS(sprintf('%s/sim_results.rds', save_folder))

sim_results |> names()
sim_results$shrinkage_results$nb |> names()

ranks = 1:length(sim_results$shrinkage_results[['nb']][['matdecomp_svd']])
allcells_mse = sim_results$estimate_matapprox

    # 5.3 shrinkage changes
    plot_df = NULL
    for(est_method in names(sim_results$shrinkage_results)) {
      plot_df_ = sim_results$shrinkage_results[[est_method]][['matcomp_linearreg']] |> # pick any (would be same)
                        dplyr::mutate(method = 'unshrunk', rank = NA) |>
                        dplyr::mutate(shrinkage_point = unshrunk_value,   # set all values to the original estimates
                                      shrunk_value    = unshrunk_value, 
                                      lower_ci        = unshrunk_value - qnorm(1 - ALPHA/2) * se,
                                      upper_ci        = unshrunk_value + qnorm(1 - ALPHA/2) * se) 
      plot_df_ = rbind(plot_df_, 
                       sim_results$allcells_results[[est_method]] |> # all cells
                         dplyr::mutate(method = 'unshrunkallcells', rank = NA) |>
                         dplyr::mutate(shrinkage_point = NA,   # set all values to the original estimates
                                       weight = NA, 
                                       shrunk_value    = estimate,
                                       unshrunk_value  = estimate)  |> 
                         dplyr::select(all_of(colnames(plot_df_))) )
      for(approx_method in names(sim_results$shrinkage_results[[est_method]])) {
         # if there are not ranks (eg linearreg)
          if(is.data.frame(sim_results$shrinkage_results[[est_method]][[approx_method]])) {
            plot_df_ = rbind(plot_df_, 
                            sim_results$shrinkage_results[[est_method]][[approx_method]] |> 
                            dplyr::mutate(method = approx_method, rank = NA))
          } else { # if there are ranks (eg softImpute, svd, sparse svd, ..) 
            for(r in ranks) { # if there was an error estimating some subset of ranks, then this might cause issues
               plot_df_ = rbind(plot_df_, 
                            sim_results$shrinkage_results[[est_method]][[approx_method]][[r]] |> 
                            dplyr::mutate(method = approx_method, rank = r))
            }
            
          }
      }
      plot_df = rbind(plot_df, plot_df_ |> dplyr::mutate(sim_distn = est_method, .before = 1))
      rm(plot_df_)
    }
    
    plot_df$method = factor(plot_df$method, 
                            levels = c("unshrunkallcells" , "unshrunk", "matcomp_linearreg", "matcomp_softImpute", "matdecomp_svd", "matdecomp_sparsesvd"))
    plot_df = plot_df |> mutate(is_sig = !((lower_ci <= 0) & (0 <= upper_ci)))
    # mse
    ggplot(plot_df |> 
             group_by(sim_distn, method, rank) |> 
             summarize(mse = mean((shrunk_value - true_theta)^2)) |> 
             arrange(sim_distn, method, rank) |> 
             mutate(methodrank = factor(paste0(method, rank), 
                                    levels = c("unshrunkallcellsNA",
                                               "unshrunkNA", 
                                               "matcomp_linearregNA", 
                                               paste0("matcomp_softImpute", ranks), 
                                               paste0("matdecomp_svd", ranks),
                                               paste0("matdecomp_sparsesvd", ranks)))), 
           aes(x = methodrank, y = mse)) +
      geom_col(color = 'black', fill = 'gray') +
      facet_grid(rows = vars(sim_distn), scales = 'free_y') +
      coord_cartesian(ylim= c(0, .009)) +
      labs(title = sprintf('MSE   %s', substr(save_folder, nchar(save_folder) - 1, nchar(save_folder)))) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
    
    ggsave(filename = sprintf('%s/shrinkage_mse.pdf', save_folder), width = 6, height = 6)
    
    
plot_df |> 
         group_by(sim_distn, method, rank) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
         arrange(sim_distn, method, rank)
  

mse_table =        plot_df |> 
         group_by(sim_distn, method, rank) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
         arrange(sim_distn, method, rank) |> mutate(rank = replace_na(rank, 0)) |> as.data.frame()


# mse_table =        cbind(
#   plot_df |> filter(sim_distn == 'pois') |>
#          group_by(sim_distn, method, rank) |> 
#          summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
#          arrange(sim_distn, method, rank) |> mutate(rank = replace_na(rank, 0)) |> as.data.frame()
# , plot_df |> filter(sim_distn == 'nb') |>
#          group_by(sim_distn, method, rank) |> 
#          summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
#          arrange(sim_distn, method, rank) |> mutate(rank = replace_na(rank, 0)) |> as.data.frame()
# )
stargazer::stargazer(
   mse_table,
  summary = FALSE, 
  out = sprintf('%s/mse_table.html', save_folder))



# look at power and false positive rate

ggplot(plot_df |>  mutate(test_type = sapply(true_theta, function(th) {if(th==0){'Null'} else {'Alt'}}))  |>
  group_by(sim_distn, method, rank, test_type) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), 
                   rejected = mean(is_sig),
                   .groups = 'drop') |> 
         arrange(sim_distn, method, rank, test_type) |> 
         mutate(methodrank = factor(paste0(method, rank), 
                                    levels = c("unshrunkallcellsNA",
                                               "unshrunkNA", 
                                               "matcomp_linearregNA", 
                                               paste0("matcomp_softImpute", ranks), 
                                               paste0("matdecomp_svd", ranks),
                                               paste0("matdecomp_sparsesvd", ranks)))),
  aes(x = methodrank, y = rejected)) +
  geom_hline(aes(yintercept = ALPHA), color = 'orange', alpha = .7) +
  geom_col() +
  facet_grid(cols = vars(test_type), rows = vars(sim_distn)) +
  # coord_cartesian(ylim= c(0, .009)) +
  labs(title = sprintf('Proportion of Tests Rejected   %s', substr(save_folder, nchar(save_folder) - 1, nchar(save_folder)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

ggsave(filename = sprintf('%s/shrinkage_rej.pdf', save_folder), width = 6, height = 6)
```




```{r}
# read in saved results


save_folder = '../../plots/simEBCICell/C'
sim_results_C = readRDS(sprintf('%s/sim_results.rds', save_folder))

sim_results_C |> names()
sim_results_C$shrinkage_results$nb |> names()

ranks = 1:length(sim_results_C$shrinkage_results[['nb']][['matdecomp_svd']])
allcells_mse = sim_results_C$estimate_matapprox

    # 5.3 shrinkage changes
    plot_df = NULL
    for(est_method in names(sim_results_C$shrinkage_results)) {
      plot_df_ = sim_results_C$shrinkage_results[[est_method]][['matcomp_linearreg']] |> # pick any (would be same)
                        dplyr::mutate(method = 'unshrunk', rank = NA) |>
                        dplyr::mutate(shrinkage_point = unshrunk_value,   # set all values to the original estimates
                                      shrunk_value    = unshrunk_value, 
                                      lower_ci        = unshrunk_value - qnorm(1 - ALPHA/2) * se,
                                      upper_ci        = unshrunk_value + qnorm(1 - ALPHA/2) * se) 
      plot_df_ = rbind(plot_df_, 
                       sim_results_C$allcells_results[[est_method]] |> # all cells
                         dplyr::mutate(method = 'unshrunkallcells', rank = NA) |>
                         dplyr::mutate(shrinkage_point = NA,   # set all values to the original estimates
                                       weight = NA, 
                                       shrunk_value    = estimate,
                                       unshrunk_value  = estimate)  |> 
                         dplyr::select(all_of(colnames(plot_df_))) )
      for(approx_method in names(sim_results_C$shrinkage_results[[est_method]])) {
         # if there are not ranks (eg linearreg)
          if(is.data.frame(sim_results_C$shrinkage_results[[est_method]][[approx_method]])) {
            plot_df_ = rbind(plot_df_, 
                            sim_results_C$shrinkage_results[[est_method]][[approx_method]] |> 
                            dplyr::mutate(method = approx_method, rank = NA))
          } else { # if there are ranks (eg softImpute, svd, sparse svd, ..) 
            for(r in ranks) { # if there was an error estimating some subset of ranks, then this might cause issues
               plot_df_ = rbind(plot_df_, 
                            sim_results_C$shrinkage_results[[est_method]][[approx_method]][[r]] |> 
                            dplyr::mutate(method = approx_method, rank = r))
            }
            
          }
      }
      plot_df = rbind(plot_df, plot_df_ |> dplyr::mutate(sim_distn = est_method, .before = 1))
      rm(plot_df_)
    }
    
    plot_df$method = factor(plot_df$method, 
                            levels = c("unshrunkallcells" , "unshrunk", "matcomp_linearreg", "matcomp_softImpute", "matdecomp_svd", "matdecomp_sparsesvd"))
    plot_df = plot_df |> mutate(is_sig = !((lower_ci <= 0) & (0 <= upper_ci)))
    # mse
    ggplot(plot_df |> 
             group_by(sim_distn, method, rank) |> 
             summarize(mse = mean((shrunk_value - true_theta)^2)) |> 
             arrange(sim_distn, method, rank) |> 
             mutate(methodrank = factor(paste0(method, rank), 
                                    levels = c("unshrunkallcellsNA",
                                               "unshrunkNA", 
                                               "matcomp_linearregNA", 
                                               paste0("matcomp_softImpute", ranks), 
                                               paste0("matdecomp_svd", ranks),
                                               paste0("matdecomp_sparsesvd", ranks)))), 
           aes(x = methodrank, y = mse)) +
      geom_col(color = 'black', fill = 'gray') +
      facet_grid(rows = vars(sim_distn), scales = 'free_y') +
      coord_cartesian(ylim= c(0, .5)) +
      labs(title = sprintf('MSE   %s', substr(save_folder, nchar(save_folder) - 1, nchar(save_folder)))) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
    
    ggsave(filename = sprintf('%s/shrinkage_mse.pdf', save_folder), width = 6, height = 6)
    
    
plot_df |> 
         group_by(sim_distn, method, rank) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
         arrange(sim_distn, method, rank)
  

mse_table =        plot_df |> 
         group_by(sim_distn, method, rank) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
         arrange(sim_distn, method, rank) |> mutate(rank = replace_na(rank, 0)) |> as.data.frame()


# mse_table =        cbind(
#   plot_df |> filter(sim_distn == 'pois') |>
#          group_by(sim_distn, method, rank) |> 
#          summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
#          arrange(sim_distn, method, rank) |> mutate(rank = replace_na(rank, 0)) |> as.data.frame()
# , plot_df |> filter(sim_distn == 'nb') |>
#          group_by(sim_distn, method, rank) |> 
#          summarize(mse = mean((shrunk_value - true_theta)^2), .groups = 'drop') |> 
#          arrange(sim_distn, method, rank) |> mutate(rank = replace_na(rank, 0)) |> as.data.frame()
# )
stargazer::stargazer(
   mse_table,
  summary = FALSE, 
  out = sprintf('%s/mse_table.html', save_folder))

# look at power and false positive rate

ggplot(plot_df |>  mutate(test_type = sapply(true_theta, function(th) {if(th==0){'Null'} else {'Alt'}}))  |>
  group_by(sim_distn, method, rank, test_type) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2), 
                   rejected = mean(is_sig),
                   .groups = 'drop') |> 
         arrange(sim_distn, method, rank, test_type) |> 
         mutate(methodrank = factor(paste0(method, rank), 
                                    levels = c("unshrunkallcellsNA",
                                               "unshrunkNA", 
                                               "matcomp_linearregNA", 
                                               paste0("matcomp_softImpute", ranks), 
                                               paste0("matdecomp_svd", ranks),
                                               paste0("matdecomp_sparsesvd", ranks)))),
  aes(x = methodrank, y = rejected)) +
  geom_hline(aes(yintercept = ALPHA), color = 'blue', alpha = .7) +
  geom_col() +
  facet_grid(cols = vars(test_type), rows = vars(sim_distn)) +
  # coord_cartesian(ylim= c(0, .009)) +
  labs(title = sprintf('Proportion of Tests Rejected   %s', substr(save_folder, nchar(save_folder) - 1, nchar(save_folder)))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))

ggsave(filename = sprintf('%s/shrinkage_rej.pdf', save_folder), width = 6, height = 6)

```




```{r eval=FALSE}
 
# more plots showing shrinkage changes



plot_df = NULL
for(est_method in names(shrinkage_results)) {
  plot_df_ = shrinkage_results[[est_method]][['matcomp_linearreg']] |> # pick any (would be same)
                    dplyr::mutate(method = 'unshrunk', rank = NA) |>
                    dplyr::mutate(shrinkage_point = unshrunk_value,   # set all values to the original estimates
                                  shrunk_value    = unshrunk_value, 
                                  lower_ci        = unshrunk_value - qnorm(1 - ALPHA/2) * se,
                                  upper_ci        = unshrunk_value + qnorm(1 - ALPHA/2) * se) 
  for(approx_method in names(shrinkage_results[[est_method]])) {
     # if there are not ranks (eg linearreg)
      if(is.data.frame(shrinkage_results[[est_method]][[approx_method]])) {
        plot_df_ = rbind(plot_df_, 
                        shrinkage_results[[est_method]][[approx_method]] |> 
                        dplyr::mutate(method = approx_method, rank = NA))
      } else { # if there are ranks (eg softImpute, svd, sparse svd, ..) 
        for(r in ranks) { # if there was an error estimating some subset of ranks, then this might cause issues
           plot_df_ = rbind(plot_df_, 
                        shrinkage_results[[est_method]][[approx_method]][[r]] |> 
                        dplyr::mutate(method = approx_method, rank = r))
        }
        
      }
  }
  plot_df = rbind(plot_df, plot_df_ |> dplyr::mutate(sim_distn = est_method, .before = 1))
  rm(plot_df_)
}

plot_df$method = factor(plot_df$method, 
                        levels = c("unshrunk", "matcomp_linearreg", "matcomp_softImpute", "matdecomp_svd", "matdecomp_sparsesvd"))

ggplot(plot_df |> 
         group_by(sim_distn, method, rank) |> 
         summarize(mse = mean((shrunk_value - true_theta)^2)) |> 
         arrange(sim_distn, method, rank) |> 
         mutate(methodrank = factor(paste0(method, rank), 
                                levels = c("unshrunkNA", 
                                           "matcomp_linearregNA", 
                                           paste0("matcomp_softImpute", ranks), 
                                           paste0("matdecomp_svd", ranks),
                                           paste0("matdecomp_sparsesvd", ranks)))), 
       aes(x = methodrank, y = mse)) +
  geom_col(color = 'black', fill = 'gray') +
  facet_grid(rows = vars(sim_distn), scales = 'free_y')




```




# Many repetitions per setting




```{r}

# plan(multisession, workers = 8)

# simulations


ALPHA = .1 # PARAMETER
overall_save_folder = '../../plots/simEBCICell/' # dir.create(shrinkage_plots_folder)

make_plots_forall = FALSE
# repetitions_forall = 20
repetitions_forall = 3
matapprox_methods_forall = c('matcomp_linearreg', 'matcomp_softImpute', 'matdecomp_svd', 'matdecomp_sparsesvd', 'spectralbiclust', 'spectralbiclust_threshold', 'zeros', 'average')
cell_distns_forall = c('pois', 'nb')
parallel_forall = FALSE
# simulations

# === SETTING A === (small, easy, fast setting)
set.seed(12345)
setting_name = 'A'
P=5
G=10
rank=2
ThetaA = create_blocky_matrix(r = rank, n = P, m = G) # display_matrix(Theta)
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment
save_folder = sprintf('%s%s/', overall_save_folder, setting_name); dir.create(save_folder)
t0 = Sys.time()
sim_A_results = sim_EBCI_celllevel(
  ALPHA=ALPHA,            # alpha testing level (for CIs)
  P=P,                    # number of grnas/perturbations
  G=G,                    # number of genes
  rank=rank,              # true rank of theta matrix
  Theta=ThetaA,            # true effects ( input NULL if want to simulate)
  cell_distns = cell_distns_forall, # cell_distns (pois/nb)
  N=500,                 # number of treated cells
  N_control=500,          # number of control cells
  pi_P=pi_P,              # propensity score for each treatment
  nb_size=3,              # contributes to the overdispersion of NB (smaller = more overdispersed)
  ranks=c(1, 2, 3),       # ranks for matrix approximations
  matapprox_methods = matapprox_methods_forall, # matrix approx methods
  save_folder=save_folder,# folder to save results and plots
  make_plots = make_plots_forall, # whether to create plots (set to FALSE bc time)
  repetitions=repetitions_forall, # number of repetitions
  write_plot_df=FALSE,            # whether to save plot_df (set to FALSE bc this large file)
  parallel=parallel_forall        # whether to run in parallel
)

# N=500; N_control=500; nb_size=3; ranks=c(1,2,3)
t1 = Sys.time(); print(t1 - t0) # 8 sec w/o plots, 1.7 mins with plots??


# modify for many reps
setting_name = 'A'
save_folder = sprintf('../../plots/simEBCICell/%s', setting_name)
sim_results = readRDS(sprintf('%s/1/sim_results.rds', save_folder))

sim_results_filenames = grep(pattern = 'sim_results.rds', x = list.files(save_folder, recursive = TRUE, full.names = TRUE), value = TRUE)
make_plots_from_save(sim_results_filenames=sim_results_filenames,
                     save_folder=save_folder,
                     which_plots = list(matrix=FALSE, mse=TRUE, miscoverage=FALSE),
                     write_plot_df = FALSE, write_summary_df=FALSE)
gc()


cur_plot_df = read.csv(sprintf('%s/sim_results_df.csv', save_folder))
cur_plot_df |> group_by(repetition, sim_distn, split_type, method) |> summarize(count = n()) # should be P x G each
if(('matrix_individual' %in% names(which_plots)) & which_plots$matrix_individual) {print('yes')} # it evaluates both????
if(('matrix_individual' %in% names(which_plots)) ) {print('yes')}
if(('matrix_individual' %in% names(which_plots)) && which_plots$matrix_individual) {print('yes')} # need && (boolean) not & (bitwise)

save_folder
list.dirs(save_folder)
list.files(save_folder, recursive = TRUE, full.names = TRUE)
save_folder


h5_2_2_plot_matrix_individual <- function(sim_results, color_limits=NULL) {
    dir.create(sprintf('%s/mat/', save_folder))
    if(is.null(color_limits)) {
      # set limits based on slightly expanded true Theta values
      cur_min = min(sim_results$Theta)
      cur_max = max(sim_results$Theta)
      cur_middle = (cur_min + cur_max) / 2
      scaling = 1.3
      
      color_limits = c(min(-1, ceiling(scaling * (cur_min - cur_middle) + cur_middle)),
                       floor(scaling * (cur_max - cur_middle) + cur_middle))
    }
  
    my_heatmap_fill_scale = scale_fill_gradient2(midpoint = 0, limits = color_limits, low = "#3A3A98" , high = "#832424", 
                                                 breaks = c(color_limits[1], 0, color_limits[2]), 
                                                 labels = c(paste0('<', color_limits[1]), 0, paste0('>', color_limits[2]))) 
    
    #' Function to display matrix in a standard way across all these matrices
    my_display_matrix <- function(X) {
      display_matrix(X, color_limits[1], color_limits[2]) + my_heatmap_fill_scale + theme(axis.title = element_blank())
    }
    
    
    # save Theta
    pl = my_display_matrix(sim_results$Theta) + labs(title = TeX(r'(True Effects $\Theta$)')) 
    ggsave(plot = pl, filename = sprintf('%s/mat/Theta.pdf', save_folder), width = 8, height = 8)
    ggsave(plot = pl, filename = sprintf('%s/mat/Theta.png', save_folder),
           width = 8, height = 8, units = 'in', dpi = 300)
    
    
    
    # save initial estimates
    for(est_method in names(sim_results$est_effects_matrices)) {
      for(splittype in names(sim_results$est_effects_matrices[[est_method]])) {
        pl = my_display_matrix(sim_results$est_effects_matrices[[est_method]][[splittype]]) + labs(title = paste0('Estimated Effects (', splittype, ')' ))
        ggsave(plot = pl, filename = sprintf('%s/mat/esteff_%s_%s.pdf', save_folder, est_method, splittype), width = 8, height = 8)
        ggsave(plot = pl, filename = sprintf('%s/mat/esteff_%s_%s.png', save_folder, est_method, splittype),
           width = 8, height = 8, units = 'in', dpi = 300)
      }
    }
    
    
  # save shrinkage targets/matrix approximations
  for(est_method in names(sim_results$estimate_matapprox)) {
    for(splittype in names(sim_results$estimate_matapprox[[est_method]])) { # train test all
      for(approx_method in names(sim_results$estimate_matapprox[[est_method]][[splittype]])) {
        approx_method_shortname = substr(approx_method, start = nchar(approx_method) - 6, stop = nchar(approx_method))
        if(is.matrix(sim_results$estimate_matapprox[[est_method]][[splittype]][[approx_method]])) {
          pl = my_display_matrix(sim_results$estimate_matapprox[[est_method]][[splittype]][[approx_method]]) + 
               labs(title = paste0('Shrinkage Point/Matrix Approximation (', splittype, ' ', approx_method, ' ', ')' ))
          ggsave(plot = pl, filename = sprintf('%s/mat/approx_%s_%s_%s.pdf', save_folder, est_method, splittype, approx_method_shortname), width = 8, height = 8)
          ggsave(plot = pl, filename = sprintf('%s/mat/approx_%s_%s_%s.png', save_folder, est_method, splittype, approx_method_shortname),
                 width = 8, height = 8, units = 'in', dpi = 300)
        } else {
          for(r in sim_results$ranks) {
            pl = my_display_matrix(sim_results$estimate_matapprox[[est_method]][[splittype]][[approx_method]][[r]]) + 
                 labs(title = paste0('Shrinkage Point/Matrix Approximation (', splittype, ' ', approx_method, ' ', r, ')' ))
            ggsave(plot = pl, filename = sprintf('%s/mat/approx_%s_%s_%s_%s.pdf', save_folder, est_method, splittype, approx_method_shortname, r), width = 8, height = 8)
            ggsave(plot = pl, filename = sprintf('%s/mat/approx_%s_%s_%s_%s.png', save_folder, est_method, splittype, approx_method_shortname, r),
                   width = 8, height = 8, units = 'in', dpi = 300)
          }
        }
      }
    }
  }
  
  # save shrunk estimates
  for(est_method in names(sim_results$shrinkage_results)) {
    for(splittype in names(sim_results$shrinkage_results[[est_method]])) { # samplesplit or not
      if(splittype == 'samplesplit') {
        splittype_short =  'spl'
      } else if(splittype == 'nosamplesplit') {
        splittype_short =  'nospl'
      }
      
      for(approx_method in names(sim_results$shrinkage_results[[est_method]][[splittype]])) {
        approx_method_shortname = substr(approx_method, start = nchar(approx_method) - 6, stop = nchar(approx_method))
        if(is.data.frame(sim_results$shrinkage_results[[est_method]][[splittype]][[approx_method]])) {
          res_df = sim_results$shrinkage_results[[est_method]][[splittype]][[approx_method]]
          res_mat = reshape2::acast(res_df |> dplyr::select(x_idx, y_idx, shrunk_value), formula = y_idx ~ x_idx) # convert from tall df to wide mat
          
          pl = my_display_matrix(res_mat) + 
               labs(title = paste0('Shrunk Estimates (', splittype, ' ', approx_method, ' ', ')' ))
          ggsave(plot = pl, filename = sprintf('%s/mat/shrunk_%s_%s_%s.pdf', save_folder, est_method, splittype_short, approx_method_shortname), width = 8, height = 8)
          ggsave(plot = pl, filename = sprintf('%s/mat/shrunk_%s_%s_%s.png', save_folder, est_method, splittype_short, approx_method_shortname),
                 width = 8, height = 8, units = 'in', dpi = 300)
        } else {
          for(r in sim_results$ranks) {
            res_df = sim_results$shrinkage_results[[est_method]][[splittype]][[approx_method]][[r]]
            res_mat = reshape2::acast(res_df |> dplyr::select(x_idx, y_idx, shrunk_value), formula = y_idx ~ x_idx) # convert from tall df to wide mat
            
            pl = my_display_matrix(res_mat) + 
                 labs(title = paste0('Shrunk Estimates (', splittype, ' ', approx_method, ' ', r, ')' ))
            ggsave(plot = pl, filename = sprintf('%s/mat/shrunk_%s_%s_%s_%s.pdf', save_folder, est_method, splittype_short, approx_method_shortname, r), width = 8, height = 8)
            ggsave(plot = pl, filename = sprintf('%s/mat/shrunk_%s_%s_%s_%s.png', save_folder, est_method, splittype_short, approx_method_shortname, r),
                   width = 8, height = 8, units = 'in', dpi = 300)
          }
        }
      }
    }
  }
  
}
```

create plots from save
```{r}
#| eval: true
#| output: false
#| warning: false
#| include: false

# make the matrix and mse plots for all the settings
# for(setting_name in c('A', 'B', 'C', 'D', 'E', 'F', 'G')) {
for(setting_name in c('A', 'E',  'G')) {
  # load in save and create sim specific plots
  # setting_name = 'A'
  save_folder = sprintf('../../plots/simEBCICell/%s', setting_name)
  # sim_results = readRDS(sprintf('%s/sim_results.rds', save_folder))
  
  sim_results_filenames = grep(pattern = 'sim_results.rds', x = list.files(save_folder, recursive = TRUE, full.names = TRUE), value = TRUE)
  make_plots_from_save(sim_results_filenames=sim_results_filenames,
                       save_folder=save_folder,
                       which_plots = list(matrix=TRUE, mse=TRUE, miscoverage=TRUE),
                       write_plot_df = FALSE)

}



```



# Trash



```{r}

source('../../utils/simEBCICell_utils.R') 

# testing/checking get_ebci_average_pvals
setting_name = 'A'
save_folder = sprintf('../../plots/simEBCICell/%s', setting_name)
sim_results = readRDS(sprintf('%s/1/sim_results.rds', save_folder))

plot_df = read.csv(sprintf('%s/sim_results_df.csv', save_folder)) # repetition, sim_distn, split_type, method
ranks = sim_results$ranks

sim_results$shrinkage_results$nb$samplesplit$matdecomp_svd[[2]]

sim_results$allcells_results$pois


sim_results$ebci_params$nb$samplesplit$matdecomp_svd[[2]]





cur_mu2   = sim_results$ebci_params$nb$samplesplit$matdecomp_svd[[2]]$mu2['estimate']
cur_kappa = sim_results$ebci_params$nb$samplesplit$matdecomp_svd[[2]]$kappa['estimate']

shrinkage_results_df = sim_results$shrinkage_results$nb$samplesplit$matdecomp_svd[[2]]

t0 = Sys.time()
average_pvals = rep(NA, times = nrow(shrinkage_results_df))
for(i in 1:nrow(shrinkage_results_df)) {
  # i = 4
  average_pval = 
    get_ebci_average_pvals(thetashrunk = shrinkage_results_df[i, 'shrunk_value'], 
                           sigma       = shrinkage_results_df[i, 'se'], 
                           web         = shrinkage_results_df[i, 'w_eb'] , 
                           mu2         = cur_mu2, 
                           kappa       = cur_kappa,
                           alpha_threshold = .001, 
                           maxiter     = 10) 
  average_pvals[i] = average_pval
}

t1 = Sys.time(); print(t1 - t0)
average_pvals


plot(shrinkage_results_df$shrinkage_point, average_pvals)


t0 = Sys.time()
h4_1_ebci_pvals(shrinkage_results_df = sim_results$shrinkage_results$nb$samplesplit$matdecomp_svd[[2]], 
                ebci_obj = sim_results$ebci_params$nb$samplesplit$matdecomp_svd[[2]])
t1 = Sys.time(); print(t1 - t0)



shrinkage_results_df = sim_results$shrinkage_results$nb$samplesplit$matdecomp_svd[[2]]
head(shrinkage_results_df)


# 
ggplot(shrinkage_results_df |> mutate(isTheta0 = (true_theta == 0)),
       aes(x = ebci_pvals, group = isTheta0, fill = isTheta0)) +
  geom_histogram()




# qqplot: pvals vs unif(0,1) 
# want the p-vals to be ~ unif(0,1) [aka on the diagonal] for theta==0, and off diagonal (beneath) for theta!=0 
ggplot(plot_df |> mutate(isTheta0 = (true_theta == 0)),
       aes(sample = ebci_pvals, group = isTheta0, color = isTheta0, fill = isTheta0)) +
  geom_abline(aes(slope = 1, intercept = 0)) +
  geom_qq(distribution = stats::qunif) +
  
  labs(title = 'QQ-plot of Inverted EBCI p-values vs Unif(0,1)')

#' Plot qqplots of the inverted ebci p-values
#' 
#'
#'
#' @param plot_df (dataframe) that contains the columns: 
h_plot_ebcipval <- function(plot_df, ranks, save_folder) {
  # CI Coverage (should be 1-alpha proportion) # Mis-coverage rate to compare with mse (lower is better)
  # How to combine p-values for each test? eg for pert p --> gene g, there are 20 tests and 20 p-values. How do we combine? I think it is also fine to just append in these qqplots, but we can also try Fisher's method?
  # checking if Fisher's test will preserve unif(0,1). However, we would get an inflated power for tha alternates, right? eg, bc it is acting like a meta analysis where we have 20x the sample size/experiments
  
  if(FALSE) {
    df_unif = data.frame(rep = rep(1:100, each = 10),
                         pval = runif(n = 1000, min = 0, max = 1))
    fishers_method <- function(x) {-2 * sum(log(x, base = exp(1)))}
    fishers_pval <- function(s) {1 - pchisq(s, df = 2*10)} #df k = 10????
    df_unif |> group_by(rep) |> summarize(fishers_stat = fishers_method(pval)) |> mutate(fishers_pval = fishers_pval(fishers_stat)) |> pull(fishers_pval) |> hist()
    
    
    ggplot(df_unif |> group_by(rep) |> summarize(fishers_stat = fishers_method(pval)) |> mutate(fishers_pval = fishers_pval(fishers_stat)), 
           aes(sample = fishers_pval)) + 
      geom_abline(aes(slope = 1, intercept = 0)) +
      geom_qq(distribution = stats::qunif)
  }
  
  
  
  isTheta0NamedFunc <- function(b) {if(b){'Null'} else {'Alt'}}
  
  # === QQ-Plot: One Run/Repetition
  
  
  if("repetition" %in% colnames(plot_df)) { 
    chosen_rep = min(plot_df$repetition)
    plot_df_one = plot_df |> filter(repetition == chosen_rep)
  } else {
    plot_df_one = plot_df
  }
  # qqplot: pvals vs unif(0,1) 
  # want the p-vals to be ~ unif(0,1) [aka on the diagonal] for theta==0, and off diagonal (beneath) for theta!=0 
  p_ebci_pvals = ggplot(plot_df_one |>
                          mutate(isTheta0 = (true_theta == 0)) |> 
                          mutate(methodrank = factor(paste0(method, rank), 
                                 levels = c("unshrunkallcellsNA",
                                           "unshrunkNA", 
                                           "matcomp_linearregNA", 
                                           paste0("matcomp_softImpute", ranks), 
                                           paste0("matdecomp_svd", ranks),
                                           paste0("matdecomp_sparsesvd", ranks), 
                                           paste0("spectralbiclust", ranks), 
                                           paste0("spectralbiclust_threshold", ranks), 
                                           "zerosNA", 
                                           "averageNA"))) |>
                           mutate(isTheta0Named = sapply(FUN = isTheta0NamedFunc, X = isTheta0)),
                        aes(sample = ebci_pvals, group = methodrank, color = methodrank, fill = methodrank)) +
                geom_abline(aes(slope = 1, intercept = 0)) +
                geom_qq(distribution = stats::qunif) +
                coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
                labs(title = 'QQ-plot of Inverted EBCI p-values vs Unif(0,1)') + 
                facet_grid(rows = vars(sim_distn), cols = vars(split_type, isTheta0Named), scales = "fixed") +
                theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), panel.grid.major.x = element_blank())
  
  ggsave(filename = sprintf('%s/ebci_pvals_one.pdf', save_folder), plot = p_ebci_pvals, width = 10, height = 5) 
  
  rm(plot_df_one)
  
  # === QQ-Plot: all repetitions, combined through Fisher's comb
  
  fishers_methodf <- function(x) {-2 * sum(log(x, base = exp(1)))}
  fishers_pvalf <- function(s, k) {1 - pchisq(s, df = 2*k)}
  
  plot_df_fishers = plot_df |>  mutate(isTheta0 = (true_theta == 0)) |> group_by(gene, grna, sim_distn, split_type, method, rank, isTheta0) |> summarize(meanp = mean(ebci_pvals), fisher_stat = fishers_methodf(ebci_pvals), count = n())
  plot_df_fishers$fishers_pval = mapply(FUN = fishers_pvalf, s= plot_df_fishers$fisher_stat, k = plot_df_fishers$count) 
    
    
  plot_df_fishers = plot_df_fishers |> 
                          mutate(methodrank = factor(paste0(method, rank), 
                                 levels = c("unshrunkallcellsNA",
                                           "unshrunkNA", 
                                           "matcomp_linearregNA", 
                                           paste0("matcomp_softImpute", ranks), 
                                           paste0("matdecomp_svd", ranks),
                                           paste0("matdecomp_sparsesvd", ranks), 
                                           paste0("spectralbiclust", ranks), 
                                           paste0("spectralbiclust_threshold", ranks), 
                                           "zerosNA", 
                                           "averageNA"))) |>
                         mutate(isTheta0Named = sapply(FUN = isTheta0NamedFunc, X = isTheta0))
  # at least this fishers combined pval should tell us for nulls?
  p_ebci_pvals = ggplot(plot_df_fishers,  aes(sample = fishers_pval, group = methodrank, color = methodrank, fill = methodrank)) +
      geom_abline(aes(slope = 1, intercept = 0)) +
      geom_qq(distribution = stats::qunif) +
      coord_cartesian(xlim = c(0, 1), ylim = c(0, 1)) +
      labs(title = 'QQ-plot of Fisher Combined Inverted EBCI p-values vs Unif(0,1)') + 
      facet_grid(rows = vars(sim_distn), cols = vars(split_type, isTheta0Named), scales = "fixed") +
      theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), panel.grid.major.x = element_blank())

  
  
  ggsave(filename = sprintf('%s/ebci_pvals_fishers.pdf', save_folder), plot = p_ebci_pvals, width = 10, height = 5) 
  
}











method_nicenames = c("unshrunkallcells"="Original (Full Dataset)",
                     "unshrunk"="Original", 
                     "matcomp_linearreg"="Linear Regression", 
                     "matcomp_softImpute"="softImpute", 
                     "matdecomp_svd"="SVD",
                     "matdecomp_sparsesvd"="Sparse SVD", 
                     "spectralbiclust"="Spectral Biclustering", 
                     "spectralbiclust_threshold"="Spectral Biclustering w/ Thresholding", 
                     "zeros"="Zeros", 
                     "average"="Average")

rank_nicenames = paste0('(rank=', 1:100, ')')



methodrank_nicenames <- function(method_name, rank_) {
  # method_name = 'zeros'
  # rank_ = 2
  # rank_ = NA
  # methodrank_nicenames(method_name = plot_df_summ$method[1], rank_ = plot_df_summ$rank[1]) |> unname()
  # mapply(FUN = methodrank_nicenames, method_name =  plot_df_summ$method[1:4], rank_ = plot_df_summ$rank[1:4]) |> unname()

  
  if(is.na(rank_)) {
    return(method_nicenames[method_name] |> unname())
  } else {
    return(paste0(method_nicenames[method_name], ' ', rank_nicenames[rank_]) |> unname())
  }
  
}


# make the ordering for a various number of methodrank levels (even if not used): first method according to method_nicenames, then rank NA, 1, 2, ...
methodrank_nicenames_order = c()
for(cur_method in names(method_nicenames)) {
  for(cur_rank in c(NA, 1:10)) {
    methodrank_nicenames_order = c(methodrank_nicenames_order, methodrank_nicenames(method_name = cur_method, rank_ = cur_rank) |> unname())
  }
}


plot_df_summ = plot_df |> 
       filter(method != 'matcomp_linearreg') |> # exclude this... this performs badly
       group_by(sim_distn, split_type, method, rank) |> 
       summarize(mse = mean((shrunk_value - true_theta)^2)) |> mutate(methodrank = paste0(method, rank)) |>
       mutate(sim_distn = factor(sim_distn, levels = c('pois', 'nb'), labels = c('Poisson', 'Negative Binomial')),
              split_type = factor(split_type, levels = c('nosamplesplit', 'samplesplit'), labels = c('Full Dataset', 'Sample Split')))

plot_df_summ$methodrank = mapply(FUN = methodrank_nicenames, method_name =  plot_df_summ$method, rank_ = plot_df_summ$rank) |> unname()
plot_df_summ$methodrank = factor(plot_df_summ$methodrank, levels = methodrank_nicenames_order)

original_all_mse = plot_df_summ |> filter(method == 'unshrunkallcells')


library(paletteer)
distinct_colors = paletteer::paletteer_d("colorBlindness::paletteMartin") 
distinct_colors[c(2, 4, 6, 7, 12, 14)]

methodrank_colors = 
c( colorRampPalette(c("white", distinct_colors[2]))(2 + 1)[1:2+1], # (original)
  colorRampPalette(c("white", distinct_colors[4]))(length(ranks) + 1)[1:length(ranks)+1], # softImpute
  colorRampPalette(c("white", distinct_colors[6]))(length(ranks) + 1)[1:length(ranks)+1], # SVD
  colorRampPalette(c("white", distinct_colors[7]))(length(ranks) + 1)[1:length(ranks)+1], # Sparse SVD
  # colorRampPalette(c("white", distinct_colors[12]))(length(ranks) + 1)[1:length(ranks)+1], # biclustering
  colorRampPalette(c("white", distinct_colors[14]))(2 + 1)[1:2+1] # zeros/avg
  )


sim_distn_nicename = c('pois'= 'Poisson', 'nb'='Negative Binomial')
split_type_nicename = c('nosamplesplit'='Full Dataset', 'samplesplit'='Sample Split')

ggplot() +
      geom_col(data = plot_df_summ, aes(x = methodrank, y = mse, fill = methodrank), color = 'black', alpha = 1) + # MSEs
      geom_hline(data = original_all_mse, aes(yintercept = mse), color = '#DB1A1A', linewidth = .7) +                   # MSEs for 'naive'/original method
      facet_grid(rows = vars(sim_distn), cols = vars(split_type), scales = 'free_y', 
                 # labeller = as_labeller(c(sim_distn_nicename, split_type_nicename))
                 labeller = label_value
                 ) +
      scale_fill_discrete(palette = methodrank_colors) +
      labs(title = 'MSE', x = 'method + rank', y = 'mse', fill = 'Method') +
      scale_y_continuous(expand = expansion(mult = c(0, .05))) +
      theme(# axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
            panel.grid.major.x = element_blank(), strip.background = element_rect(fill = NA), 
            axis.ticks.x = element_blank())
```



```{r}
# install.packages('biclust') # Warning: package 'biclust' is not available for this version of R
# https://search.r-project.org/CRAN/refmans/biclust/html/BCSpectral.html
# archived, so install from tar.gz file
# https://cran.r-project.org/src/contrib/Archive/biclust/    
# use newest 	biclust_2.0.3.tar.gz   from 2021
# install.packages("C:/Users/Cathe/Downloads/biclust_2.0.3.tar.gz", repos = NULL, type="source")

library(biclust)

# Random matrix with embedded bicluster  
test <- matrix(rnorm(5000),100,50)
test[11:20,11:20] <- rnorm(100,10,0.1)
image(test)

shuffled_test <- test[sample(nrow(test)), sample(ncol(test))]
image(shuffled_test)

# Without specifying the  number of row and column clusters
res1 <- spectral(shuffled_test,normalization="irrc", numberOfEigenvalues=3, 
                 minr=2, minc=2, withinVar=1, n_clusters = NULL, n_best = 3)
res1

order(res1@info$row_labels)
res1@info




row_cl = data.frame(row_idx = 1:nrow(shuffled_test), 
                    row_cl  = res1@info$row_labels)
col_cl = data.frame(col_idx = 1:ncol(shuffled_test), 
                    col_cl  = res1@info$column_labels)

bicluster_assignment = merge(reshape2::melt(shuffled_test, varnames = c('row_idx', 'col_idx'), value.name = 'value'), 
                             tidyr::expand_grid(row_cl, col_cl) |> dplyr::select(row_idx, col_idx, row_cl, col_cl), 
                             by = c('row_idx', 'col_idx'))

biclust_mean = bicluster_assignment |> dplyr::group_by(row_cl, col_cl) |> dplyr::summarise(bicl_mean = mean(value))


merge(bicluster_assignment, 
      biclust_mean, 
      by = c('row_cl', 'col_cl')) |> dplyr::select(row_idx, col_idx, bicl_mean)

biclust_mat = reshape2::acast(merge(bicluster_assignment, biclust_mean, by = c('row_cl', 'col_cl')) |> 
                                dplyr::select(row_idx, col_idx, bicl_mean) |> dplyr::arrange(row_idx, col_idx), 
                              row_idx ~ col_idx, value.var="bicl_mean")
image(biclust_mat)
image(biclust_mat[order(res1@info$row_labels), order(res1@info$column_labels)])

image(shuffled_test[order(res1@info$row_labels), order(res1@info$column_labels)])


# Specifying the  number of row and column clusters
res2 <- spectral(shuffled_test,normalization="log", numberOfEigenvalues=6, 
                 minr=2, minc=2, withinVar=1, n_clusters = 2, n_best = 3)
res2
image(shuffled_test[order(res2@info$row_labels), order(res2@info$column_labels)])
    


    
    mat = shuffled_test
    r = 3
    Theta_rownames = paste0('grna', 1:nrow(mat))
    Theta_colnames = paste0('gene', 1:ncol(mat))


    spbicl_res = spectral(mat,
                 # normalization = "bistochastization",
                 # normalization = "irrc", # log, irrc, bistochastization (in example, bistochastization made could not find cl??)
                 normalization = "log", # they recommend log even w their example matrix of negative values?
                 numberOfEigenvalues = r, # here use ranks? or n_best?
                 minr=2, minc=2, withinVar=2, n_clusters = NULL, 
                 n_best = 3 # #e.vecs to which the data is projected for the final clustering step, recommended values are 2 or 3. but maybe we should do more?
                 )
    
    row_cl = data.frame(row_idx = row.names(mat), 
                        row_cl  = spbicl_res@info$row_labels)
    col_cl = data.frame(col_idx = colnames(mat), 
                        col_cl  = spbicl_res@info$column_labels)

    bicluster_assignment = merge(reshape2::melt(mat, varnames = c('row_idx', 'col_idx'), value.name = 'value'), 
                                 tidyr::expand_grid(row_cl, col_cl) |> dplyr::select(row_idx, col_idx, row_cl, col_cl), 
                                 by = c('row_idx', 'col_idx'))
   
    
    biclust_mean = bicluster_assignment |> dplyr::group_by(row_cl, col_cl) |> dplyr::summarise(bicl_mean = mean(value), bicl_sd = sd(value), count = dplyr::n())
    nbiclusters = nrow(biclust_mean) 
    # zero out if pval is sig dif from 0 w bonferonni correction at alpha=.05 (very rough)
    # from normalization procedure and biclustering, each bicluster should have sd around 1, I think?
    biclust_mean = biclust_mean |> dplyr::mutate(zstat = (bicl_mean - 0)/(bicl_sd/sqrt(count)), pval = pnorm(-abs(zstat)), zeroed = as.integer(pval > .05/nbiclusters), bicl_mean_zeroed = (1 - zeroed) * bicl_mean)
    
    

    biclust_mat = reshape2::acast(merge(bicluster_assignment, biclust_mean, by = c('row_cl', 'col_cl')) |> 
                                    dplyr::select(row_idx, col_idx, bicl_mean) |> dplyr::arrange(row_idx, col_idx), 
                                  row_idx ~ col_idx, value.var="bicl_mean")
    row.names(biclust_mat) = Theta_rownames; colnames(biclust_mat) = Theta_colnames
    
    
    
    biclust_mat_zeroed = reshape2::acast(merge(bicluster_assignment, biclust_mean, by = c('row_cl', 'col_cl')) |> 
                                    dplyr::select(row_idx, col_idx, bicl_mean_zeroed) |> dplyr::arrange(row_idx, col_idx), 
                                  row_idx ~ col_idx, value.var="bicl_mean_zeroed")
    row.names(biclust_mat) = Theta_rownames; colnames(biclust_mat) = Theta_colnames
    
    # image(biclust_mat[order(spbicl_res@info$row_labels), order(spbicl_res@info$column_labels)])
    # image(biclust_mat_zeroed[order(spbicl_res@info$row_labels), order(spbicl_res@info$column_labels)])

    mat_approx_res[[r]] = biclust_mat
    
    
    
shuffled_test
    
# test h3_1_1
    
library(biclust)

source('../../utils/simEBCICell_utils.R')

# setting_name = 'E'
setting_name = 'A'
save_folder = sprintf('../../plots/simEBCICell/%s', setting_name)
sim_results = readRDS(sprintf('%s/1/sim_results.rds', save_folder)) # first run

sim_results$shrinkage_results$pois$samplesplit$zeros


mat = sim_results$est_effects_matrices$nb$train

image(sim_results$Theta)
image(mat)
image(shuffled_test)
dim(mat)
dim(shuffled_test)



    
h3_1_approximate_matrix(mat = mat,  
                        method = 'spectralbiclust', ranks = c(1, 2, 3), Theta_rownames=paste0('grna', 1:nrow(mat)), Theta_colnames=paste0('gene', 1:ncol(mat)))



setting_name = 'E'
save_folder = sprintf('../../plots/simEBCICell/%s', setting_name)
sim_results = readRDS(sprintf('%s/1/sim_results.rds', save_folder)) # first run

mat = sim_results$est_effects_matrices$nb$train

a = h3_1_approximate_matrix(mat = mat,  
                        method = 'spectralbiclust', ranks = c(1, 2), Theta_rownames=paste0('grna', 1:nrow(mat)), Theta_colnames=paste0('gene', 1:ncol(mat)))
```


```{r eval=FALSE}
set.seed(12345)
ALPHA = .1 # PARAMETER
# simulate values at the cell sample level 
P = 5  # number of perturbations/treatments
G = 10 # number of genes/outcomes
N = 1000        # sample size- number of cells getting treatment perturbations
N_control = 500 # sample size- number of control cells
pi_P = runif(P, min = .3, max = .7); pi_P = pi_P / sum(pi_P) # propensity score for each treatment

rank = 2 # true rank of theta matrix
nb_size = 3 # contributes to the overdispersion of NB? (smaller, more overdispersed?)
ranks = c(1, 2, 3) # ranks for matrix approx methods 

# constant_coef = 1 # overall mean (mean for untreated/control cells)
constant_coef = runif(n = G, min = .1, max = 2) # overall mean across genes (mean for untreated/control cells)

# create names 
matrix_rownames = sprintf("grna%04.f", 1:P) # should be adaptive to #digits ceiling(nrow(cur_estimates_matrix) / 10)
matrix_colnames = sprintf("gene%04.f", 1:G)

# treatment effects 
Theta = create_blocky_matrix(r = rank, n = P, m = G)
row.names(Theta) = matrix_rownames
colnames(Theta) = matrix_colnames

# assign perturbation/grna treatment
grna = list()
grna$train =  t(rmultinom(n=N, size=1, prob=pi_P)) # n x p (#cells x #perturbations)
grna$test =  t(rmultinom(n=N, size=1, prob=pi_P)) 
# grna = t(rmultinom(n=N, size=1, prob=pi_P)) # n x p (#cells x #perturbations)
# grna_factor = apply(X=grna, MARGIN=1, FUN = function(v) {which(v==1)}) |> 
#               factor() # factor version of grna (which is one-hot encoded)









# simulate data...
cell_mean_effects = list()
cell_mean_effects$train = matrix(rep(constant_coef, times = N), byrow = TRUE, nrow = N) + grna$train %*% Theta
cell_mean_effects$test  = matrix(rep(constant_coef, times = N), byrow = TRUE, nrow = N) + grna$test  %*% Theta



# observed counts for each cell across genes
counts           = list()
counts[['pois']] = list()
counts[['nb']]   = list()

counts$pois$train = matrix(NA, nrow = N, ncol = G) # treated cells # train
counts$pois$test  = matrix(NA, nrow = N, ncol = G)                 # test 
counts$nb$train   = matrix(NA, nrow = N, ncol = G)                 # train 
counts$nb$test    = matrix(NA, nrow = N, ncol = G)                 # test  

counts$pois_control$train = matrix(NA, nrow = N_control, ncol = G) # control cells # train
counts$pois_control$test  = matrix(NA, nrow = N_control, ncol = G)                 # test
counts$nb_control$train   = matrix(NA, nrow = N_control, ncol = G)                 # train 
counts$nb_control$test    = matrix(NA, nrow = N_control, ncol = G)                 # test 

for(j in 1:G) {
  counts$pois$train[,j] = rpois(  n=N,                lambda = exp(cell_mean_effects$train[,j])) 
  counts$pois$test[,j]  = rpois(  n=N,                lambda = exp(cell_mean_effects$test[,j])) 
  counts$nb$train[,j]   = rnbinom(n=N, size = nb_size,    mu = exp(cell_mean_effects$train[,j]))
  counts$nb$test[,j]    = rnbinom(n=N, size = nb_size,    mu = exp(cell_mean_effects$test[,j]))
  
  counts$pois_control$train[,j] = rpois(  n=N_control,                lambda = exp(constant_coef[j])) 
  counts$pois_control$test[,j] = rpois(  n=N_control,                lambda = exp(constant_coef[j])) 
  counts$nb_control$train[,j]    = rnbinom(n=N_control, size = nb_size,    mu = exp(constant_coef[j]))
  counts$nb_control$test[,j]    = rnbinom(n=N_control, size = nb_size,    mu = exp(constant_coef[j]))
  
}



# am i stupid? we could either do: 
# (1) gene g ~ grna p for each (g, p) or
# (2) gene g ~ \vec{grna} for each g (treat perturbations as levels in a categorical variable)
# these should be the same (as long as there aren't other variables, eg confounders) because
# the only variables are the treatment
# (but when there are other variables, (2) is better bc you can then use a large sample size for the
#  estimation of those coefficients. But, I think SCEPTRE does it one by one (1), so i will do it
#  this way in the simulation)
# (i mean, if you think that the confounders effect the outcome differently for each population,
#  cells w pert 1 vs cells w pert 2, then you should do (1). But that seems maybe unlikely, and it
#  would probably be helpful to be able to pool information from the larger sample size of cells)



# Do 'naively' at first: for each (i,j) pair, perform glm fit
t0 = Sys.time()
est_effects_matrices = list()
est_se_matrices = list()
for(est_method in c('pois', 'nb')) {
  est_effects_matrices[[est_method]] = list()
  est_se_matrices     [[est_method]] = list()
  for(split in c('train', 'test', 'all')) {
    est_effects_matrices[[est_method]][[split]] = matrix(NA, nrow = P, ncol = G, dimnames = list(matrix_rownames, matrix_colnames))  
    est_se_matrices     [[est_method]][[split]] = matrix(NA, nrow = P, ncol = G, dimnames = list(matrix_rownames, matrix_colnames))  
    
    
    # estimate
    for(i in 1:P) {
      # # indices of cells w pert i
      # switch(split,
      #        'all'=
      #        {pert_i_idx = c(which(grna[['train']][,i] == 1), 
      #                        which(grna[['test' ]][,i] == 1))},
      #        # default: train or test
      #        {pert_i_idx = which(grna[[split]][,i] == 1)})

      
      for(j in 1:G) {
        if(split == 'all') {
          pert_i_idx_train = which(grna[['train']][,i] == 1)
          cur_dfij_train = data.frame(Y = c(counts[[est_method]][['train']][pert_i_idx_train,j], counts[[paste0(est_method, '_control')]][['train']][,j]),
                                A = c(rep(1, times = length(pert_i_idx_train)), rep(0, times = N_control)))
          pert_i_idx_test = which(grna[['test']][,i] == 1)
          cur_dfij_test = data.frame(Y = c(counts[[est_method]][['test']][pert_i_idx_test,j], counts[[paste0(est_method, '_control')]][['test']][,j]),
                                A = c(rep(1, times = length(pert_i_idx_test)), rep(0, times = N_control)))
          cur_dfij = rbind(cur_dfij_train, cur_dfij_test)
        } else { # train or test
          pert_i_idx = which(grna[[split]][,i] == 1)
          cur_dfij = data.frame(Y = c(counts[[est_method]][[split]][pert_i_idx,j], counts[[paste0(est_method, '_control')]][[split]][,j]),
                                A = c(rep(1, times = length(pert_i_idx)), rep(0, times = N_control)))
        }
        
        if(est_method == 'pois') {
          glm_fit =       glm(   formula = 'Y ~ 1 + A', data = cur_dfij, family = poisson())
        } else if(est_method == 'nb') {
          glm_fit   = MASS::glm.nb(formula = 'Y ~ 1 + A', data = cur_dfij)
        }
        
        est_effects_matrices[[est_method]][[split]][i,j] = as.numeric(glm_fit$coefficients['A'])
        est_se_matrices     [[est_method]][[split]][i,j] = summary(glm_fit)$coefficients['A', 'Std. Error']
        
        
        
      }
    }
  }
}
# 
# est_effects_pois = matrix(NA, nrow = P, ncol = G, dimnames = list(matrix_rownames, matrix_colnames))  
# est_effects_nb   = matrix(NA, nrow = P, ncol = G, dimnames = list(matrix_rownames, matrix_colnames)) 
# est_se_pois  = matrix(NA, nrow = P, ncol = G, dimnames = list(matrix_rownames, matrix_colnames))
# est_se_nb    = matrix(NA, nrow = P, ncol = G, dimnames = list(matrix_rownames, matrix_colnames)) 
# for(i in 1:P) {
#   pert_i_idx = which(grna[,i] == 1) # indices of cells w pert i
#   for(j in 1:G) {
#     
#     cur_dfij = data.frame(Y_pois = c(counts_pois[pert_i_idx,j], counts_pois_control[,j]),
#                           Y_nb   = c(counts_nb[pert_i_idx,j]  , counts_nb_control[,j]  ),
#                           A      = c(rep(1, times = length(pert_i_idx)), rep(0, times = N_control)))
#     
#     pois_fit =       glm(   formula = 'Y_pois ~ 1 + A', data = cur_dfij, family = poisson())
#     nb_fit   = MASS::glm.nb(formula =   'Y_nb ~ 1 + A', data = cur_dfij)
# 
#     est_effects_pois[i,j] = as.numeric(pois_fit$coefficients['A'])
#     est_effects_nb[i,j]   = as.numeric(  nb_fit$coefficients['A'])
#     
#     est_se_pois[i,j] = summary(pois_fit)$coefficients['A', 'Std. Error']
#     est_se_nb[i,j]   = summary(  nb_fit)$coefficients['A', 'Std. Error']
#     
#   }
# }
t1 = Sys.time(); print(t1 - t0)

allcells_results = list()
for(est_method in c('pois', 'nb')) {
  
  cur_df = 
    merge(reshape2::melt(est_effects_matrices[[est_method]][['all'  ]], value.name = 'estimate', varnames = c('grna', 'gene')),
          merge(reshape2::melt(est_effects_matrices[[est_method]][['all'  ]] - qnorm(1 - ALPHA/2) * est_se_matrices[[est_method]][['all'  ]], 
                   value.name = 'lower_ci', varnames = c('grna', 'gene')), 
                reshape2::melt(est_effects_matrices[[est_method]][['all'  ]] + qnorm(1 - ALPHA/2) * est_se_matrices[[est_method]][['all'  ]], 
                   value.name = 'upper_ci', varnames = c('grna', 'gene')), 
                by = c('grna', 'gene')), 
          by = c('grna', 'gene'))
  cur_df = merge(merge(cur_df, 
                       data.frame(y_idx = 1:length(matrix_rownames), grna = matrix_rownames),
                       by = 'grna'), 
                 data.frame(x_idx = 1:length(matrix_colnames), gene = matrix_colnames),
                 by = 'gene')
  allcells_results[[est_method]] = cur_df
  rm(cur_df)
  
}





# the effects are the coef from glm... take log transform for ATE? no bc i transformed in the sim already... only do this at one of the stages
# i think it should be this ay because e ant our estimates to be asymptotically normal, but this on't be true if e then take a transformation
display_matrix(est_effects_matrices$pois$train)
display_matrix(est_effects_matrices$pois$test)
display_matrix(est_effects_matrices$nb$train)
display_matrix(est_effects_matrices$nb$test)





# Matrix Decomp/Approximation
estimate_matapprox = list()
estimate_matapprox_plots = list()
for(est_method in c('pois', 'nb')) {
  estimate_matapprox      [[est_method]] = list()
  estimate_matapprox_plots[[est_method]] = list()
  
  for(split in c('train', 'test')) {
    estimate_matapprox      [[est_method]][[split]] = list()
    estimate_matapprox_plots[[est_method]][[split]] = list()
    cur_mat = est_effects_matrices[[est_method]][[split]] # matrix to make approximations of
    n = nrow(cur_mat); m = ncol(cur_mat)
    
    
    # === matrix completion methods (linear reg, softImpute)
    # --- Linear Reg
    estimate_matapprox[[est_method]][[split]][['matcomp_linearreg']] =  
                     matrix(NA, nrow = n, ncol = m, dimnames = list(matrix_rownames, matrix_colnames))
    for(i in 1:n) {
      for(j in 1:m) {
        estimate_matapprox[[est_method]][[split]][['matcomp_linearreg']][i,j] = linearreg(cur_mat, i, j)
      }
    }
    estimate_matapprox_plots[[est_method]][[split]][['matcomp_linearreg']] = display_matrix(estimate_matapprox[[est_method]][[split]][['matcomp_linearreg']])
    
    
    # --- softImpute
    estimate_matapprox      [[est_method]][[split]][['matcomp_softImpute']] = list()
    estimate_matapprox_plots[[est_method]][[split]][['matcomp_softImpute']] = list()
    for(r in ranks) {
      estimate_matapprox[[est_method]][[split]][['matcomp_softImpute']][[r]] = 
                     matrix(NA, nrow = n, ncol = m, dimnames = list(matrix_rownames, matrix_colnames))
      matcomp_fun = create_matrix_completion_softImpute(X = cur_mat, rank_max = r, type = 'als') 
      for(i in 1:n) {
        for(j in 1:m) {
          estimate_matapprox[[est_method]][[split]][['matcomp_softImpute']][[r]][i,j] = matcomp_fun(i, j)
        }
      }
      estimate_matapprox_plots[[est_method]][[split]][['matcomp_softImpute']][[r]] =
                              display_matrix(estimate_matapprox[[est_method]][[split]][['matcomp_softImpute']][[r]])
    }
    
    
    # === matrix decomposition methods (svd, sparse svd, etc...)
    estimate_matapprox      [[est_method]][[split]][['matdecomp_svd']]       = list()
    estimate_matapprox      [[est_method]][[split]][['matdecomp_sparsesvd']] = list()
    estimate_matapprox_plots[[est_method]][[split]][['matdecomp_svd']]       = list()
    estimate_matapprox_plots[[est_method]][[split]][['matdecomp_sparsesvd']] = list()
    
    svdres = svd(cur_mat, nu = max(ranks), nv = max(ranks))
    cv.out = PMA::SPC.cv(cur_mat, sumabsvs = seq(1.2, min(5, sqrt(n), sqrt(m)), len = 10))
    pmd_res = PMA::SPC(cur_mat, sumabsv=cv.out$bestsumabsv, K = max(ranks))
    for(r in ranks) {
      # --- SVD
      cur_matapprox = svdres$u[, 1:r, drop=FALSE] %*% diag(svdres$d[1:r], nrow=r, ncol=r) %*% t(svdres$v[, 1:r, drop=FALSE]) # take up to r eigenvectors
      row.names(cur_matapprox) = matrix_rownames; colnames(cur_matapprox) = matrix_colnames
      estimate_matapprox[[est_method]][[split]][['matdecomp_svd']][[r]] = cur_matapprox
      estimate_matapprox_plots[[est_method]][[split]][['matdecomp_svd']][[r]] = display_matrix(cur_matapprox)
      rm(cur_matapprox)
      
      # --- Sparse SVD
      cur_matapprox = pmd_res$u[, 1:r, drop=FALSE] %*% diag(pmd_res$d[1:r], nrow=r, ncol=r) %*% t(pmd_res$v[, 1:r, drop=FALSE]) # take up to r eigenvectors
      row.names(cur_matapprox) = matrix_rownames; colnames(cur_matapprox) = matrix_colnames
      estimate_matapprox[[est_method]][[split]][['matdecomp_sparsesvd']][[r]] = cur_matapprox
      estimate_matapprox_plots[[est_method]][[split]][['matdecomp_sparsesvd']][[r]] = display_matrix(cur_matapprox)
      rm(cur_matapprox)
    
    
    
    }
  }
}

  
if(F) {
  
estimate_matapprox = list()
estimate_matapprox$pois = list()
estimate_matapprox$nb   = list()

estimate_matapprox_plots = list()
estimate_matapprox_plots$pois = list()
estimate_matapprox_plots$nb   = list()


ranks = c(1, 2, 3)
for(est_method in names(est_effects_matrices)) {
  cur_mat = est_effects_matrices[[est_method]] # matrix to make approximations of
  n = nrow(cur_mat); m = ncol(cur_mat)
  # === matrix completion methods (linear reg, softImpute)
  # --- Linear Reg
  estimate_matapprox[[est_method]][['matcomp_linearreg']] =  
                   matrix(NA, nrow = n, ncol = m, dimnames = list(matrix_rownames, matrix_colnames))
  for(i in 1:n) {
    for(j in 1:m) {
      estimate_matapprox[[est_method]][['matcomp_linearreg']][i,j] = linearreg(cur_mat, i, j)
    }
  }
  estimate_matapprox_plots[[est_method]][['matcomp_linearreg']] = display_matrix(estimate_matapprox[[est_method]][['matcomp_linearreg']])
  
  
  # --- softImpute
  estimate_matapprox      [[est_method]][['matcomp_softImpute']] = list()
  estimate_matapprox_plots[[est_method]][['matcomp_softImpute']] = list()
  for(r in ranks) {
    estimate_matapprox[[est_method]][['matcomp_softImpute']][[r]] = 
                   matrix(NA, nrow = n, ncol = m, dimnames = list(matrix_rownames, matrix_colnames))
    matcomp_fun = create_matrix_completion_softImpute(X = cur_mat, rank_max = r, type = 'als') 
    for(i in 1:n) {
      for(j in 1:m) {
        estimate_matapprox[[est_method]][['matcomp_softImpute']][[r]][i,j] = matcomp_fun(i, j)
      }
    }
    estimate_matapprox_plots[[est_method]][['matcomp_softImpute']][[r]] =
                            display_matrix(estimate_matapprox[[est_method]][['matcomp_softImpute']][[r]])
  }
  
  
  # === matrix decomposition methods (svd, sparse svd, etc...)
  estimate_matapprox[[est_method]][['matdecomp_svd']]             = list()
  estimate_matapprox[[est_method]][['matdecomp_sparsesvd']]       = list()
  estimate_matapprox_plots[[est_method]][['matdecomp_svd']]       = list()
  estimate_matapprox_plots[[est_method]][['matdecomp_sparsesvd']] = list()
  
  svdres = svd(cur_mat, nu = max(ranks), nv = max(ranks))
  cv.out = PMA::SPC.cv(cur_mat, sumabsvs = seq(1.2, min(5, sqrt(n), sqrt(m)), len = 10))
  pmd_res = PMA::SPC(cur_mat, sumabsv=cv.out$bestsumabsv, K = max(ranks))
  for(r in ranks) {
    # --- SVD
    cur_matapprox = svdres$u[, 1:r, drop=FALSE] %*% diag(svdres$d[1:r], nrow=r, ncol=r) %*% t(svdres$v[, 1:r, drop=FALSE]) # take up to r eigenvectors
    row.names(cur_matapprox) = matrix_rownames; colnames(cur_matapprox) = matrix_colnames
    estimate_matapprox[[est_method]][['matdecomp_svd']][[r]] = cur_matapprox
    estimate_matapprox_plots[[est_method]][['matdecomp_svd']][[r]] = display_matrix(cur_matapprox)
    rm(cur_matapprox)
    
    # --- Sparse SVD
    cur_matapprox = pmd_res$u[, 1:r, drop=FALSE] %*% diag(pmd_res$d[1:r], nrow=r, ncol=r) %*% t(pmd_res$v[, 1:r, drop=FALSE]) # take up to r eigenvectors
    row.names(cur_matapprox) = matrix_rownames; colnames(cur_matapprox) = matrix_colnames
    estimate_matapprox[[est_method]][['matdecomp_sparsesvd']][[r]] = cur_matapprox
    estimate_matapprox_plots[[est_method]][['matdecomp_sparsesvd']][[r]] = display_matrix(cur_matapprox)
    rm(cur_matapprox)
    
  }
}

}




# EBCI to arbitrary point


# use shrink_matrix from utils/matrix_shrinkage.r
t0 = Sys.time()
shrinkage_results = list()
for(est_method in names(estimate_matapprox)) {
  shrinkage_results[[est_method]] = list()
  
  cur_estimates_mat = est_effects_matrices[[est_method]][['train']] # matrix of estimates to shrink
  cur_se_mat        = est_se_matrices[[est_method]][['train']]      # matrix of se's of est to shrink
  
  for(approx_method in names(estimate_matapprox[[est_method]][['test']])) {
    # # could test by using: is.matrix or is.list
    # is.matrix(estimate_matapprox[[est_method]][['matdecomp_sparsesvd']])
    # is.matrix(estimate_matapprox[[est_method]][['matcomp_linearreg']])
    # is.list(estimate_matapprox[[est_method]][['matdecomp_sparsesvd']])
    # is.list(estimate_matapprox[[est_method]][['matcomp_linearreg']])
    
    # if there are not ranks (eg linearreg)
    if(is.matrix(estimate_matapprox[[est_method]][['test']][[approx_method]])) {
      cur_shrinkagepoint_mat = estimate_matapprox[[est_method]][['test']][[approx_method]]
      
      # shrink matrix
      cur_shrink_res = 
        shrink_matrix(unshrunk_mat = cur_estimates_mat,
                    shrinkpoint_mat = cur_shrinkagepoint_mat,
                    se_mat = cur_se_mat,
                    ALPHA = ALPHA,
                    return_ebci_obj=FALSE,
                    weight_mat=NULL)
      # add true theta values
      cur_shrink_res = merge(cur_shrink_res, 
                             reshape2::melt(Theta, varnames = c('grna', 'gene'), value.name = 'true_theta'),
                             by = c('grna', 'gene'))
      # add idx for plotting later
      cur_shrink_res = merge(merge(cur_shrink_res, 
                                   data.frame(y_idx = 1:length(matrix_rownames), grna = matrix_rownames),
                                   by = 'grna'), 
                             data.frame(x_idx = 1:length(matrix_colnames), gene = matrix_colnames),
                             by = 'gene')
      # save result
      shrinkage_results[[est_method]][[approx_method]] = cur_shrink_res

      
    } else { # if there are ranks (eg softImpute, svd, sparse svd, ..) 
      for(r in ranks) { # if there was an error estimating some subset of ranks, then this might cause issues
        cur_shrinkagepoint_mat = estimate_matapprox[[est_method]][['test']][[approx_method]][[r]]
        # shrink matrix
        cur_shrink_res = 
          shrink_matrix(unshrunk_mat = cur_estimates_mat,
                      shrinkpoint_mat = cur_shrinkagepoint_mat,
                      se_mat = cur_se_mat,
                      ALPHA = ALPHA,
                      return_ebci_obj=FALSE,
                      weight_mat=NULL)
        # add true theta values
        cur_shrink_res = merge(cur_shrink_res, 
                               reshape2::melt(Theta, varnames = c('grna', 'gene'), value.name = 'true_theta'),
                               by = c('grna', 'gene'))
        # add idx for plotting later
        cur_shrink_res = merge(merge(cur_shrink_res, 
                                     data.frame(y_idx = 1:length(matrix_rownames), grna = matrix_rownames),
                                     by = 'grna'), 
                               data.frame(x_idx = 1:length(matrix_colnames), gene = matrix_colnames),
                               by = 'gene')
        # save result
        shrinkage_results[[est_method]][[approx_method]][[r]] = cur_shrink_res
        
      }
      
    }
  }
}
t1 = Sys.time(); print(t1 - t0)







# plot the results (estimated vs true)

# use plot_shrink_results from utils/matrix_shrinkage.r
t0 = Sys.time()
# shrinkage_plots_results = list()
shrinkage_plots_folder = '../../plots/simEBCICell/' # dir.create(shrinkage_plots_folder)
for(est_method in names(shrinkage_results)) { # pois or nb
  
  assertthat::assert_that(dir.exists(shrinkage_plots_folder))
  
  for(approx_method in names(shrinkage_results[[est_method]])) {
    # # could test by using: is.matrix or is.list... should use list so it is consistent across different loops
    # is.matrix(shrinkage_results[[est_method]][['matdecomp_sparsesvd']])
    # is.matrix(shrinkage_results[[est_method]][['matcomp_linearreg']])
    # is.list(shrinkage_results[[est_method]][['matdecomp_sparsesvd']])
    # is.list(shrinkage_results[[est_method]][['matcomp_linearreg']])
    # is.data.frame(shrinkage_results[[est_method]][['matdecomp_sparsesvd']])
    # is.data.frame(shrinkage_results[[est_method]][['matcomp_linearreg']])
    
    # if there are not ranks (eg linearreg)
    if(is.data.frame(shrinkage_results[[est_method]][[approx_method]])) {
      cur_shrinkage_plots_folder = sprintf('%s%s/', shrinkage_plots_folder, approx_method)
      dir.create(sprintf('%spoints/', cur_shrinkage_plots_folder), showWarnings = FALSE, recursive = TRUE)
      cur_shrink_res = shrinkage_results[[est_method]][[approx_method]]
      
      plot_shrink_results(shrink_df      = cur_shrink_res, 
                            plot_folder    = cur_shrinkage_plots_folder, 
                            order_rowscols = FALSE, 
                            grna_index     = NULL, 
                            gene_index     = NULL, 
                            unshrunk_ALPHA = ALPHA)
      
      
      
    } else { # if there are ranks (eg softImpute, svd, sparse svd, ..) 
      for(r in ranks) { # if there was an error estimating some subset of ranks, then this might cause issues
        cur_shrinkage_plots_folder = sprintf('%s/%s_%02.f/', shrinkage_plots_folder, approx_method, r)
        dir.create(sprintf('%spoints/', cur_shrinkage_plots_folder), showWarnings = FALSE, recursive = TRUE)
        cur_shrink_res = shrinkage_results[[est_method]][[approx_method]][[r]]
        
        plot_shrink_results(shrink_df      = cur_shrink_res, 
                            plot_folder    = cur_shrinkage_plots_folder, 
                            order_rowscols = FALSE, 
                            grna_index     = NULL, 
                            gene_index     = NULL, 
                            unshrunk_ALPHA = ALPHA)
      }
    }
    

  }
}
t1 = Sys.time(); print(t1 - t0)





saveRDS(object = shrinkage_results, file = sprintf('%sshrinkage_results.rds', shrinkage_plots_folder))



```



```{r eval=FALSE}
 
# make new plots to compare results

# # ok just do it  by hand
# chosen_rank_to_plot = 3 # choose a rank for the plots
# est_method = 'nb'
# est_effects_matrices[[est_method]]
# shrinkage_results[[est_method]]  







```





```{r eval=FALSE}

# add original estimates ---------------------------------------------------
# (all the loaded dfs should have these) (2x for plotting)


plot_df = rbind(shrink_df |> 
                  dplyr::mutate(approxmethod = 'shrunk'),
                shrink_df |>
                  dplyr::mutate(rank = 'unshrunk') |>
                  dplyr::mutate(shrinkage_point = unshrunk_value,   # set all values to the original estimates
                                shrunk_value    = unshrunk_value, 
                                lower_ci        = unshrunk_value - qnorm(.95) * se,
                                upper_ci        = unshrunk_value + qnorm(.95) * se) 
)
n_subsample = 100 # subsample for display

 # === Shrinkage Changes ===
  
  set.seed(12345)
  subsample_idx = sample(1:nrow(plot_df), min(10000, nrow(plot_df)))
  
  # plot shrunk vs unshrunk
  p1 = ggplot(plot_df[subsample_idx, ] |> filter(rank != 'unshrunk')) +
    geom_abline(aes(slope = 1, intercept = 0), color = 'gray', alpha = .6) +
    geom_point(aes(x = unshrunk_value, y = shrunk_value, color = se)) +
    labs(title = 'Shrunk vs Unshrunk Estimates', x = 'unshrunk', y = 'shrunk') +
    coord_cartesian(xlim = c(-2, 2), ylim = c(-2, 2)) +
    facet_grid(cols = vars(rank)) +
    theme_classic()
  
  # ggsave(plot = p1, filename = sprintf('%spoints/shrunkvsunshrunk.pdf', plot_folder), height = 6, width = 7)
  
  
  # plot shrunk vs unshrunk centered
  p2 = ggplot(plot_df[subsample_idx, ] |> filter(rank != 'unshrunk')) +
    geom_abline(aes(slope = 1, intercept = 0), color = 'gray') +
    geom_point(aes(x = unshrunk_value - shrinkage_point, y = shrunk_value - shrinkage_point, color = se)) +
    labs(title = 'Shrunk vs Unshrunk Estimates Centered', x = 'unshrunk - shrinkage point', y = 'shrunk - shrinkage point') +
    coord_cartesian(xlim = c(-2, 2), ylim = c(-2, 2)) +
    facet_grid(# rows = vars(approxmethod),
      cols = vars(rank)) +
    theme_classic()
  
  # ggsave(plot = p2, filename = sprintf('%spoints/shrunkvsunshrunkcent.pdf', plot_folder), height = 6, width = 7)
  
  
  # plot unshrunk vs shrinkage point
  p3 = ggplot(plot_df[subsample_idx, ] |> filter(rank != 'unshrunk')) +
    geom_abline(aes(slope = 1, intercept = 0), color = 'gray') +
    geom_point(aes(x = shrunk_value, y = shrinkage_point, color = se)) +
    labs(title = 'Shrinkage Point vs Shrunk Estimates', x = 'shrunk', y = 'shrinkage point') +
    coord_cartesian(xlim = c(-2, 2), ylim = c(-2, 2)) +
    facet_grid(# rows = vars(approxmethod),
      cols = vars(rank)) +
    theme_classic()
  
  # ggsave(plot = p3, filename =sprintf('%spoints/shrinkptvsshrunk.pdf', plot_folder), height = 6, width = 7)
  
  
  
  
  
  
  
  # === Shrinkage CIs ===
  set.seed(12345)
  # get the same gene/grna tests across all methods and ranks (to be better visually, should do to prev plots too)
  sample_tests = plot_df |> filter(rank == 'unshrunk') |> slice_sample(n = 15) |> select(grna, gene) |> mutate(x = 1:n())
  plot_df_sample = merge(plot_df, sample_tests, all.x = FALSE, all.y = TRUE)
  
  # plot_df_sample |> group_by(approxmethod, rank) |> summarize(count = n()) # should all be nrow(sample_tests)
  
  
  p_CI = ggplot(plot_df_sample # |> filter(rank == 'rank=15' & approxmethod == 'lowrank') #|> 
                # slice(seq(from = 1, to = n(), by = floor(n()/400))) |>
                # slice(sample_idx) |>
                # mutate(# test = factor(test, levels = c('negative', 'positive', 'discovery')),
                #        x = 1:n()),
                ,
                aes(x = x)) +
    # geom_point(aes(y = lower_ci) )+
    # geom_point(aes(y = upper_ci)) +
    # geom_point(aes(y = -1.5)) +
    # geom_hline(aes(yintercept = 0)) +
    # ---- Shrunk CIs ---
    geom_segment(aes(x = x + .25, y = lower_ci, yend = upper_ci),
                 lineend = 'square', linewidth = 1, alpha = .7, color = 'deepskyblue4') +
    # --- Unshrunk CIs ---
    geom_segment(aes(x = x, 
                     y    = unshrunk_value - qnorm(.95)*se, 
                     yend = unshrunk_value + qnorm(.95)*se),
                 lineend = 'square', linewidth = 1, alpha = .7, color = 'deepskyblue2') +
    # geom_segment(aes(y    = eval(parse(text = CIlower_colname)), 
    #                  yend = eval(parse(text = CIupper_colname))),
    #              lineend = 'square', linewidth = 1, alpha = .7, color = 'deepskyblue4') +
    
    # --- Arrow showing shrinkage
    geom_segment(aes(x = x, xend = x+.2,
                     y =    unshrunk_value, 
                     yend = .99 * shrunk_value + .01 * unshrunk_value),
                 lineend = 'square', linejoin = 'bevel', arrow = arrow(length = unit(0.2,"cm")),
                 linewidth = .3, alpha = .7, color = 'deepskyblue2') +
    # geom_segment(aes(y = eval(parse(text = unshrunk_colname)), 
    #                  yend = .99 * eval(parse(text = shrunk_colname)) + 
    #                    .01 * eval(parse(text = unshrunk_colname))),
    #              lineend = 'square', linejoin = 'bevel', arrow = arrow(length = unit(0.2,"cm")),
    #              linewidth = .3, alpha = .7, color = 'deepskyblue2') +
    # --- Unshrunk Point---
    geom_point(aes(x = x      , y = unshrunk_value), color = 'deepskyblue2') +
    # --- Shrunk Point ---
    geom_point(aes(x = x + .25, y = shrunk_value), shape=18, color = 'deepskyblue4') +
    # --- Shrinkage Point---
    geom_point(aes(x = x + .25, y = shrinkage_point), shape=5, color = 'deepskyblue4') +
    # geom_point(aes(y = eval(parse(text = unshrunk_colname))), color = 'deepskyblue2') +
    # geom_point(aes(y = eval(parse(text =   shrunk_colname))), color = 'deepskyblue4') +
    scale_x_continuous(expand = c(0, 0), breaks = seq(0, 1000, by = 10),
                       # limits = c(1, 90)) +
                       # limits = c(65, 175)) +
                       # limits = c(95, 400)) +
                       # limits = c(1, 400)) +
    ) +
    # scale_y_continuous(expand = c(0.025, 0)) +
    coord_cartesian(ylim = c(-2, 2)) +
    labs(x = 'AY Test', y = 'Estimates',
         title = 'Before and After Robust EBCI') +
    facet_grid(# rows = vars(approxmethod),
      cols = vars(rank)) +
    theme_bw() +
    theme(panel.grid.minor.x = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank(),
          # legend.position = 'inside',
          # legend.position.inside = legend_position,
          legend.background = element_rect(color = 'black'))
  
  
  # ggsave(plot = p_CI, filename = sprintf('%spoints/CIs.pdf', plot_folder), height = 6, width = 15)
  ggsave(plot = p_CI, filename = sprintf('%sCIs.pdf', plot_folder), height = 6, width = 15)
  
  # 90% CI lengths before and after 
  set.seed(12345)
  p_CI_len = ggplot(plot_df[sample(x=1:nrow(plot_df), size = min(10000, nrow(plot_df))), ] |> 
                      mutate(unshrunk_ci_length = 2*qnorm(.95)*se,
                             shrunk_ci_length = upper_ci - lower_ci)) +
    geom_abline(aes(intercept = 0, slope = 1)) +
    geom_point(aes(x = unshrunk_ci_length, y = shrunk_ci_length), alpha = .8) +
    labs(x = 'Unshrunk CI Lengths', y = 'Shrunk CI Lengths', title = 'CI Lengths') +
    facet_grid(#rows = vars(approxmethod),
      cols = vars(rank)) +
    theme_classic()
  
  # ggsave(plot = p_CI_len, filename =sprintf('%spoints/CIlen.pdf', plot_folder), height = 6, width = 7)
  ggsave(plot = p_CI_len, filename =sprintf('%s/CIlen.pdf', plot_folder), height = 6, width = 7)
  





```




```{r eval=FALSE}
# testing stuff 


if(F) {
  set.seed(1234)
se = runif(n=100, min=.01, max=2)
theta = runif(n=100, min=-1, max=1)
simData = data.frame(unshrunk_value = mapply(FUN = rnorm, n=1, mean = theta, sd = se),
                     se = se)

simData = perf_simple_ebci(simData, formula = 'unshrunk_value ~ 0')


gridExtra::grid.arrange(grobs = make_plots(simData), nrow = 2)

  dim(grna)
dim(Theta)

t(grna) %*% Theta 
dim(t(grna) %*% Theta)
table(t(grna) %*% Theta)

# testing glm simulation gives correct effects 
set.seed(123)
sim_df = data.frame(A = rbinom(n = 1000, size = 1, prob = .5))
constant_coef = 1
treatment_effect = .5
effects_mat = matrix(c(treatment_effect), nrow = 1, ncol = 1)


# pois
sim_df$Y_pois = rpois(n=nrow(sim_df), lambda = exp(constant_coef + sim_df$A %*% effects_mat)) # will be larger matrix w mult treatments
# pois_fit = glm.fit(x=sim_df[,c('A'), drop=FALSE], y = sim_df$Y, family = poisson())
pois_fit = glm(formula = 'Y_pois ~ 1 + A', data = sim_df, family = poisson())

# negative binomial
# nb=number of bern(p) flips until size successes
# mean mu = size * (1-p)/p , and variance mu/p 
sim_df$Y_nb = rnbinom(n=nrow(sim_df), size = 3,  mu = exp(constant_coef + sim_df$A %*% effects_mat))
nb_fit = MASS::glm.nb(formula = 'Y_nb ~ 1 + A', data = sim_df)

ggplot(reshape2::melt(sim_df, id.vars = c('A'), measure.vars = c('Y_pois', 'Y_nb'), variable.name = 'distribution', value.name = 'value')) + 
  geom_histogram(aes(x = value), binwidth = 1, color = 'black', fill = 'gray') + 
  facet_grid(distribution ~ A) +
  theme_bw() +
  theme(panel.grid.minor = element_blank())







pois_fit$coefficients
nb_fit$coefficients


rpois(n=5, lambda=c(1, 2, 3, 4, 5))
sim_df$A %*% matrix(c(2), nrow = 1, ncol = 1) # will be larger matrix w mult treatments



}

```

